[workspace]
resolver = "2"
members = ["dnd-types", "dnd-ui"]

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dnd-types = { path = "dnd-types" }

[build]
rustflags = ["-Z", "threads=8"]
