[application]

# dioxus project name
name = "DnD"

# default platform
# you can also use `dx serve/build --platform XXX` to use other platform
# value: web | desktop
default_platform = "desktop"

# Web `build` & `serve` dist path
out_dir = "dist"

# resource (static) file folder
asset_dir = "assets"

# hot reload by default
hot_reload = true

[web.wasm_opt]
# The level wasm-opt should target. z is the smallest. 4 is the fastest.
level = "4"

[web.app]

# HTML title tag content
title = "Dioxus | An elegant GUI library for Rust"

[web.watcher]

index_on_404 = true

watch_path = ["src", "server", "assets", "types", "ui", "input.css"]

[bundler]
# Bundle identifier
identifier = "com.miitto.dnd"

# Bundle publisher
publisher = "Miitto"

# Bundle icon
icon = ["icons/icon.png"]

# Bundle resources
resources = ["assets/*"]

# Bundle short description
short_description = "An amazing dioxus application."

# Bundle long description
long_description = """
An amazing dioxus application.
"""
